name: flce
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - numpy=1.20.3
  - pandas=1.3.4
  - matplotlib=3.5.2
  - seaborn=0.11.2
  - scikit-learn=1.1.3
  - scipy=1.7.1
  - tqdm=4.62.3
